#!/bin/bash

# Konversi waktu ke Jakarta
sudo timedatectl set-timezone Asia/Jakarta
sudo timedatectl set-ntp true

# Cek waktu
timedatectl

# Restart cronjob
service cron restart
service cron status

# Buat file bash 
curl -o namechanel.sh https://raw.githubusercontent.com/koekudukuad/auto/main/namechanel.sh && chmod +x namechanel.sh


#install ffmpeg dan xz
apt install xz-utils
curl -o ffmpeg-release-amd64-static.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz 
tar xf ffmpeg-release-amd64-static.tar.xz 
cd ffmpeg-*-amd64-static 
cp ffmpeg /usr/local/bin/ 
cp ffprobe /usr/local/bin/ 
ffmpeg -version

